### ISSUE TITLE
Add elements to target to UI.

### ISSUE THREAD

**Issue by cpriest** [cpriest/SnapLinksPlus#301]
[ ] Create a Prefs section of "elements to target" in a "primary action" category.
[ ] Add UI for selecting different elements to target for primary action.

** Idea of above:** the "sectioned" area of prefs is so that if/when we get alternate activator options, we can easily migrate the options selection to a per-activator scenario.

Related to #177

**Comment by cpriest** [comment]
# Todo Items
- [ ] Create Storage Proxy subclass of OverlayProxy with hooks:
  - [ ] To do debounced saves of changed preferences
  - [ ] To disseminate changes to clients; not sure this is necessary now, but StorageProxy may need to listen for onChange events from the storage manager to upadate local instances.
- [ ] Update existing preferences object to be multi-level and use StorageProxy
- [ ] Create a migration snippet to translate from old to new preference structure
